# Generated by Django 4.2.6 on 2024-03-24 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='numero',
            field=models.IntegerField(),
        ),
    ]
