# Generated by Django 5.0 on 2024-02-28 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id_equipamento', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=20)),
                ('tag', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
            ],
        ),
    ]
