# Generated by Django 5.0.4 on 2024-05-23 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipments', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id_emprestimo', models.AutoField(primary_key=True, serialize=False)),
                ('data_emprestimo', models.DateField()),
                ('data_devolucao', models.DateField(blank=True, null=True)),
                ('equipamento', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipments.equipamento')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.usuario')),
            ],
        ),
    ]
