# Generated by Django 4.2.7 on 2024-04-01 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0001_initial'),
        ('gantt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gantt',
            name='equipment',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipments.equipamento'),
        ),
    ]
