# Generated by Django 5.0.4 on 2024-07-01 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gantt', '0003_alter_gantt_responsible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gantt',
            name='responsible',
        ),
    ]
